# Displays as site title on top nav bar
title: Jekyll Documentation theme

port: 4001
highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      sidebar: home
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      sidebar: generic
  -
    scope:
      path: ""
      type: "apidocs"
    values:
      layout: "default"
      tooltip: true


exclude:
  - Gemfile
  - Gemfile.lock


####### Algolia configuration ###########
algolia:
  application_id: "HXUBJERYYB"
  index_name: "documentation-theme-jekyll-next-version"
  record_css_selector: 'p,ul,.summary'
