language: japanese

# Link to home
url: /

# link to github repo
github_editme_path: https://github.com/tomjohnson1492/documentation-theme-jekyll-next-version/blob/gh-pages/
github_edit_button_text: 編集

top_navbar_color: inverse
#blue --> use "inverse"
#black --> use "default"

port: 4000
highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs_ja:
    output: true
  tags_ja:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      tag_group: taglist
  -
    scope:
      path: ""
      type: "docs_ja"
    values:
      layout: "default"
      topnav: topnav_ja
      tag_group: taglist_ja
  -
    scope:
      path: ""
      type: "tags_ja"
    values:
      layout: "default"
      topnav: topnav_ja
      sidebar: taglist_ja
      toc: false
      github_button: false

exclude:
  - Gemfile
  - Gemfile.lock
  - index_en.md
  - index_de.md


########## UI text ###############

# Displays as site title on top nav bar and on site metadata
title: Jekyllドキュメンテーションテーマ
# Displays as site description meta
description: ジキルウェブサイトのドキュメントテーマ
search_placeholder: サーチ ...
minitoc_title: 目次

tag_terms:
  product: 製品
  page: ページ
  excerpt: 抜粋
  tag_page_intro: 以下のページにはタグが付けられています

github_edit_button_text: 私を編集する
