# Displays as site title on top nav bar and on site metadata
title: Jekyll Documentation theme

# Displays as site description meta
description: Documentation theme for Jekyll websites

# Link to home
url: /

# link to github repo
github_editme_path: http://github.com/tomjohnson1492/documentation-theme-jekyll-next-version/blob/gh-pages/pages/

port: 4001
highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      sidebar: home
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      sidebar: generic
  -
    scope:
      path: ""
      type: "apidocs"
    values:
      layout: "default"
      tooltip: true


exclude:
  - Gemfile
  - Gemfile.lock


####### Algolia configuration ###########
algolia:
  application_id: "HXUBJERYYB"
  index_name: "documentation-theme-jekyll"
  record_css_selector: 'p,ul,.summary'
